### ISSUE TITLE
Can not connect to Concourse using self-signed cert

### ISSUE THREAD

**Issue by patrickcrocker** [jwfriese/FrequentFlyer#6]
I can login to a valid SSL cert backed Concourse:
- https://ci.anvil.pcfdemo.com/

But I can't login to a self-signed SSL cert backed Concourse:
- https://concourse.anvil.pcfdemo.com/

Also can't login to non-SSL Concourse:
- http://concourse.anvil.pcfdemo.com/

**Comment by jwfriese** [comment]
Thanks for filing the issue @patrickcrocker ! I'm looking into this right now.

**Comment by jwfriese** [comment]
Hey @patrickcrocker, thanks again for filing the issue. 

I've created a [story in our backlog](https://www.pivotaltracker.com/story/show/151771954) to allow you to connect to a Concourse instance with a self-signed cert, provided the user acknowledges that the cert of the Concourse instance could not be used to validate a trusted host. 

I'm less apt to allow the app to connect to a Concourse over HTTP. I'd hate to facilitate anyone accidentally getting credentials sniffed. I suppose if this use case is really common, we could add this ability in a future story. Maybe there are ways to make sure that users don't put their data at risk. 

I'll notify here when the story is done, and again when we release the update to the store!

**Comment by jwfriese** [comment]
Hi @patrickcrocker, today I pushed the new feature to implement this as I articulated in my last comment. 

This will be in the next release, 1.3.0. I'll leave this issue open until then.

**Comment by jwfriese** [comment]
1.3.0 has been released! Closing this guy
